OPENAI_API_KEY = "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"
LAT = 40.7908711
LON = -73.3746079